### ISSUE TITLE
Invalid notebook when click two of the Power User Developer notebooks in samples

### ISSUE THREAD

**Issue by BobBooth** [Esri/arcgis-python-api#2298]
When  I click the openstreetmap_exploration.ipynb and the tour_the_world_with_landsat_imagery_and_raster_functions.ipynb in this repo, I get an "Invalid Notebook" error.

https://github.com/Esri/arcgis-python-api/blob/master/samples/02_power_users_developers/openstreetmap_exploration.ipynb
"Invalid Notebook
There was an error rendering your Notebook: the 'application/vnd.jupyter.widget-state+json' key is missing from json
Using nbformat v5.10.4 and nbconvert v7.16.6"

https://github.com/Esri/arcgis-python-api/blob/master/samples/02_power_users_developers/tour_the_world_with_landsat_imagery_and_raster_functions.ipynb

"Invalid Notebook
There was an error rendering your Notebook: the 'application/vnd.jupyter.widget-state+json' key is missing from json
Using nbformat v5.10.4 and nbconvert v7.16.6"

**Comment by nanaeaubry** [comment]
@xlt208 Can you advise on this? Bob is part of ESRI so you can message on teams for more info if needed

**Comment by nanaeaubry** [comment]
@BobBooth This is due to the new widget not being supported in the version of notebook son github. We have to remove any instance where the widget is being rendered and replace with a screenshot.

cc @jyaistMap

**Comment by nanaeaubry** [comment]
This has been addressed

**Comment by BobBooth** [comment]
@nanaeaubry 
I'm still seeing the error on two of then=m

<img width="1169" height="525" alt="Image" src="https://github.com/user-attachments/assets/a6f50e7f-6011-48c7-a3ed-a49c2c303b80" />

<img width="1466" height="807" alt="Image" src="https://github.com/user-attachments/assets/5db51528-4875-4782-9f17-8ce82aa379d1" />

**Comment by nanaeaubry** [comment]
@ManushiM Please connect with Bob via teams or email to get this resolved within our samples
